-- See https://wiki.hyprland.org/Configuring/Monitors/

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
	output = "desc:LG Electronics LG ULTRAGEAR+ 401NTWG55801",
	mode = "3840x2160@144.05",
	position = "0x0",
	scale = "1",
	vrr = 1,
	bitdepth = 8,
})

hl.monitor({
	output = "desc:BNQ BenQ LCD V7G11754019",
	mode = "2560x1440@60",
	position = "3840x300",
	scale = "1",
})

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
	leaf = "windows",
	enabled = true,
	speed = 7,
	bezier = "myBezier",
})
hl.animation({
	leaf = "windowsOut",
	enabled = true,
	speed = 7,
	bezier = "default",
	style = "popin 80%",
})
hl.animation({
	leaf = "border",
	enabled = true,
	speed = 10,
	bezier = "default",
})
hl.animation({
	leaf = "fade",
	enabled = true,
	speed = 7,
	bezier = "default",
})
hl.animation({
	leaf = "workspaces",
	enabled = true,
	speed = 6,
	bezier = "default",
})

local mainMod = "SUPER"
local ipc = "noctalia msg "

hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + + + SHIFT + q", hl.dsp.window.close())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("dolphin"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + f", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind("ALT + SPACE", hl.dsp.exec_cmd(ipc .. "panel-toggle launcher"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())

hl.bind(mainMod .. " + s", hl.dsp.focus({ monitor = "+1" }))

hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

-- Bring workspace `id` to the focused monitor. If it is currently showing on
-- the other monitor, swap the two instead so that monitor keeps something.
local function summon_workspace(id)
	local active = hl.get_active_monitor()
	for _, mon in ipairs(hl.get_monitors()) do
		if mon.id ~= active.id and mon.active_workspace and mon.active_workspace.id == id then
			hl.dispatch(hl.dsp.workspace.swap_monitors({ monitor1 = active.name, monitor2 = mon.name }))
		end
	end
	hl.dispatch(hl.dsp.workspace.move({ workspace = id, monitor = active.name }))
	hl.dispatch(hl.dsp.focus({ monitor = active.name }))
	hl.dispatch(hl.dsp.focus({ workspace = id }))
end

for i = 1, 9 do
	hl.bind(mainMod .. " + " .. i, function()
		summon_workspace(i)
	end)
end

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8, follow = false }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10, follow = false }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

local volume_up = "pamixer -u -i 2 --allow-boost"
local volume_down = "pamixer -d 2"
local toggle_mute = "pamixer -t"
local volume_changed_sound = "paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"
local current_mic = "alsa_input.usb-BLUE_MICROPHONE_Blue_Snowball_201507-00.pro-input-0.2"

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(volume_up .. " && " .. volume_changed_sound))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(volume_down .. " && " .. volume_changed_sound))

hl.bind("XF86AudioMute", hl.dsp.exec_cmd(toggle_mute))
hl.bind("SHIFT + XF86AudioMute", hl.dsp.exec_cmd(toggle_mute .. " --default-source"))

hl.bind(mainMod .. " + m", hl.dsp.layout("swapwithmaster master"))
hl.bind(mainMod .. " + code:21", hl.dsp.layout("addmaster"))
hl.bind(mainMod .. " + code:20", hl.dsp.layout("removemaster"))

hl.bind(mainMod .. " + CTRL + code:47", hl.dsp.exec_cmd("systemctl suspend"))

hl.bind(mainMod .. " + SHIFT + s", hl.dsp.exec_cmd(ipc .. "screenshot-region"))

local hypremoji = "/home/caleb/rgits/HyprEmoji/target/release/hypremoji"
hl.bind("SUPER + period", hl.dsp.exec_cmd(hypremoji))
hl.window_rule({
	match = {
		title = "^(HyprEmoji)$",
	},
	float = true,
})

hl.window_rule({
	match = { class = "dev.noctalia.Noctalia" },
	float = true,
	size = { 1080, 920 },
})

hl.layer_rule({
	name = "noctalia",
	match = {
		namespace = "^noctalia-(bar-.+|notification|dock|panel|attached-panel|osd|window-switcher)$",
	},
	no_anim = true,
	ignore_alpha = 0.5,
	blur = true,
	blur_popups = true,
})

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",
		follow_mouse = 1,
		touchpad = {
			natural_scroll = false,
		},
		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
		numlock_by_default = true,
	},
	general = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		gaps_in = 0,
		gaps_out = 0,
		border_size = 1,
		col = {
			active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
			inactive_border = "rgba(595959aa)",
		},
		layout = "master",
	},
	decoration = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		rounding = 0,
		blur = {
			enabled = true,
			size = 3,
			passes = 1,
			new_optimizations = true,
		},
	},
	animations = {
		enabled = true,
	},
	dwindle = {
		preserve_split = true, -- you probably want this
	},
	master = {},
	gestures = {},
	-- Example per-device config
	-- See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
	-- device:epic mouse V1 {
	--     sensitivity = -0.5
	-- }
	-- Example windowrule v1
	-- windowrule = float, ^(kitty)$
	-- Example windowrule v2
	-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
	-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
	-- See https://wiki.hyprland.org/Configuring/Keywords/ for more
	-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
	-- bind = $mainMod, J, togglesplit # dwindle
	-- focus window
	-- Move focus with mainMod + arrow keys
	-- Switch workspaces with mainMod + [0-9]
	-- bind = $mainMod, 1, workspace, 1
	-- bind = $mainMod, 2, workspace, 2
	-- bind = $mainMod, 3, workspace, 3
	-- bind = $mainMod, 4, workspace, 4
	-- bind = $mainMod, 5, workspace, 5
	-- bind = $mainMod, 6, workspace, 6
	-- bind = $mainMod, 7, workspace, 7
	-- bind = $mainMod, 8, workspace, 8
	-- bind = $mainMod, 9, workspace, 9
	-- bind = $mainMod, 0, workspace, 10
	-- Move active window to a workspace with mainMod + SHIFT + [0-9]
	-- Scroll through existing workspaces with mainMod + scroll
	-- Move/resize windows with mainMod + LMB/RMB and dragging
	-- Audio keys
	-- Managing master layout
	-- clipboard maanager
	-- Screenshot;
	-- Start up
	-- exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
	-- just copied from project page. I should package this on nix packages.
	-- windowrulev2 = float, title:^(HyprEmoji)$
})

hl.workspace_rule({
	workspace = "9",
	monitor = "desc:LG Electronics LG ULTRAGEAR+ 401NTWG55801",
	persistent = true,
	default_name = "game",
})

hl.on("hyprland.start", function()
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("udiskie")
	hl.exec_cmd("noctalia")
end)

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-- For Noctalia Color templates
require("noctalia").apply_theme()
